http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - rate-limit
          - securityHeaders
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    securityHeaders:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Forwarded-Proto: https
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
          server: ''
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        permissionsPolicy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()
        referrerPolicy: same-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000

  routers:
    plex:
      entryPoints:
        - https
      middlewares:
        - chain-no-auth
      rule: Host(`plex.${DOMAIN_NAME}`)
      service: plex-svc
      tls:
        options: default

  services:
    plex-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://10.10.0.8:32400/

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS13
