api:
  dashboard: true
  insecure: true

log:
  filePath: "/etc/traefik/traefik.log"
  level: DEBUG

accessLog:
  filePath: "/etc/traefik/access.log"
  bufferingSize: 50

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        # Start of Clouflare public IP list for HTTP requests, remove this if y>
        - 172.18.0.0/16
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32

      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    forwardedHeaders:
      trustedIPs: *trustedIps
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: ${DOMAIN_NAME}
            sans:
              - '*.${DOMAIN_NAME}'
      middlewares:
        - securityHeaders@file

serversTransport:
  insecureSkipVerify: true

providers:
  providersThrottleDuration: 2s
  file:
    filename: /etc/traefik/config.yml
    watch: true
  docker:
    watch: true
    network: proxynet
    constraints: "Label(`traefik-internal-enable`, `true`)"
    defaultRule: "Host(`{{ lower (trimPrefix `/` .Name )}}.${DOMAIN_NAME}`)"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

